export interface MarcFieldDef {
  tag: string;
  description: string;
}

export const ALL_MARC_FIELDS: MarcFieldDef[] = [
  { tag: '001', description: 'Control Number' },
  { tag: '003', description: 'Control Number Identifier' },
  { tag: '005', description: 'Date and Time of Latest Transaction' },
  { tag: '006', description: 'Fixed-Length Data Elements - Additional Material Characteristics' },
  { tag: '007', description: 'Physical Description Fixed Field' },
  { tag: '008', description: 'Fixed-Length Data Elements' },
  { tag: '010', description: 'Library of Congress Control Number' },
  { tag: '015', description: 'National Bibliography Number' },
  { tag: '016', description: 'National Bibliographic Agency Control Number' },
  { tag: '020', description: 'International Standard Book Number (ISBN)' },
  { tag: '022', description: 'International Standard Serial Number (ISSN)' },
  { tag: '024', description: 'Other Standard Identifier' },
  { tag: '028', description: 'Publisher Number' },
  { tag: '035', description: 'System Control Number' },
  { tag: '040', description: 'Cataloging Source' },
  { tag: '041', description: 'Language Code' },
  { tag: '043', description: 'Geographic Area Code' },
  { tag: '050', description: 'Library of Congress Call Number' },
  { tag: '060', description: 'National Library of Medicine Call Number' },
  { tag: '082', description: 'Dewey Decimal Classification Number' },
  { tag: '084', description: 'Other Classification Number' },
  { tag: '090', description: 'Local Call Number' },
  { tag: '100', description: 'Main Entry - Personal Name' },
  { tag: '110', description: 'Main Entry - Corporate Name' },
  { tag: '111', description: 'Main Entry - Meeting Name' },
  { tag: '130', description: 'Main Entry - Uniform Title' },
  { tag: '210', description: 'Abbreviated Title' },
  { tag: '222', description: 'Key Title' },
  { tag: '240', description: 'Uniform Title' },
  { tag: '245', description: 'Title Statement' },
  { tag: '246', description: 'Varying Form of Title' },
  { tag: '250', description: 'Edition Statement' },
  { tag: '260', description: 'Publication, Distribution, etc. (Imprint)' },
  { tag: '264', description: 'Production, Publication, Distribution, Manufacture, and Copyright Notice' },
  { tag: '300', description: 'Physical Description' },
  { tag: '336', description: 'Content Type' },
  { tag: '337', description: 'Media Type' },
  { tag: '338', description: 'Carrier Type' },
  { tag: '340', description: 'Physical Medium' },
  { tag: '490', description: 'Series Statement' },
  { tag: '500', description: 'General Note' },
  { tag: '501', description: 'With Note' },
  { tag: '502', description: 'Dissertation Note' },
  { tag: '504', description: 'Bibliography, etc. Note' },
  { tag: '505', description: 'Formatted Contents Note' },
  { tag: '506', description: 'Restrictions on Access Note' },
  { tag: '508', description: 'Creation/Production Credits Note' },
  { tag: '510', description: 'Citation/References Note' },
  { tag: '511', description: 'Participant or Performer Note' },
  { tag: '520', description: 'Summary, etc.' },
  { tag: '521', description: 'Target Audience Note' },
  { tag: '526', description: 'Study Program Information Note' },
  { tag: '530', description: 'Additional Physical Form Available Note' },
  { tag: '533', description: 'Reproduction Note' },
  { tag: '538', description: 'System Details Note' },
  { tag: '546', description: 'Language Note' },
  { tag: '586', description: 'Awards Note' },
  { tag: '600', description: 'Subject Added Entry - Personal Name' },
  { tag: '610', description: 'Subject Added Entry - Corporate Name' },
  { tag: '611', description: 'Subject Added Entry - Meeting Name' },
  { tag: '630', description: 'Subject Added Entry - Uniform Title' },
  { tag: '648', description: 'Subject Added Entry - Chronological Term' },
  { tag: '650', description: 'Subject Added Entry - Topical Term' },
  { tag: '651', description: 'Subject Added Entry - Geographic Name' },
  { tag: '653', description: 'Index Term - Uncontrolled' },
  { tag: '655', description: 'Index Term - Genre/Form' },
  { tag: '700', description: 'Added Entry - Personal Name' },
  { tag: '710', description: 'Added Entry - Corporate Name' },
  { tag: '711', description: 'Added Entry - Meeting Name' },
  { tag: '730', description: 'Added Entry - Uniform Title' },
  { tag: '740', description: 'Added Entry - Uncontrolled Related/Analytical Title' },
  { tag: '752', description: 'Added Entry - Hierarchical Place Name' },
  { tag: '800', description: 'Series Added Entry - Personal Name' },
  { tag: '810', description: 'Series Added Entry - Corporate Name' },
  { tag: '811', description: 'Series Added Entry - Meeting Name' },
  { tag: '830', description: 'Series Added Entry - Uniform Title' },
  { tag: '856', description: 'Electronic Location and Access' },
];
